### ISSUE TITLE
yogo cmd crash

### ISSUE THREAD

**Issue by 26huitailang** [26huitailang/yogo#11]
```
$ yogo
2022/09/09 15:40:53 /Users/26huitailang/GolandProjects/
envFolder /Users/26huitailang/GolandProjects/config/development
panic: folder /Users/26huitailang/GolandProjects/config/development not exist: stat /Users/26huitailang/GolandProjects/config/development: no such file or directory

goroutine 1 [running]:
github.com/26huitailang/yogo/framework.(*YogoContainer).MustMake(0x144d1de20c62680f?, {0x5023288?, 0xc0005bbeb8?})
	/Users/26huitailang/gopath/pkg/mod/github.com/26huitailang/yogo@v1.0.0/framework/container.go:74 +0x48
github.com/26huitailang/yogo/framework/provider/log.(*YogoLogServiceProvider).Params(0xc00012c6e0, {0x52025c0, 0xc00049ea00})
	/Users/26huitailang/gopath/pkg/mod/github.com/26huitailang/yogo@v1.0.0/framework/provider/log/provider.go:71 +0x3c
github.com/26huitailang/yogo/framework.(*YogoContainer).Bind(0xc00049ea00, {0x5202780, 0xc00012c6e0})
	/Users/26huitailang/gopath/pkg/mod/github.com/26huitailang/yogo@v1.0.0/framework/container.go:51 +0x13b
main.main()
	/Users/26huitailang/gopath/pkg/mod/github.com/26huitailang/yogo@v1.0.0/main.go:27 +0x125
```

**Comment by 26huitailang** [comment]
配置服务初始化时，没有正确处理路径不存在的情况
